name: Dev-Smoke

on:
  push:
    branches:
      - dev
      - smoke

jobs:
  build:
    runs-on:
      - self-hosted
      - my-host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ github.sha }}
      
      - name: Determine port based on branch name
        id: determine_port
        run: |
              if [[ "${{ github.ref_name }}" == "dev" ]]; then
                echo "export CONTAINER_PORT=3000"
              elif [[ "${{ github.ref_name }}" == "smoke" ]]; then
                echo "export CONTAINER_PORT=3001"
              fi
              echo "Branch name is ${{ github.ref }}"
              echo "::set-output name=container_port::${CONTAINER_PORT}"
          
      - name: Run Docker container
        run: |
            docker run -d -p ${{ steps.determine_port.outputs.container_port }}:3000 --name ${{ github.ref_name }}-${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ github.sha }}
  
