name: Staging-Prod

on:
    push:
        branches:
          - main
          - staging
        tags:
          - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'


jobs:
  build:
    runs-on:
      - self-hosted
      - my-host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read commit hash from artifact
        id: commit_hash
        run: |
          COMMIT_HASH=$(cat ~/Desktop/NewsLetter_Website_Using_MailChamp_API/commit_hash.txt)
          echo "Commit hash from artifact: $COMMIT_HASH"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ steps.commit_hash.outputs.COMMIT_HASH }}
      
      - name: Determine port based on branch name
        id: determine_port
        run: |
            if [[ "${{ github.ref_name }}" == "staging" ]]; then
              echo "export CONTAINER_PORT=3002"
            elif [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "export CONTAINER_PORT=8080"
            fi
            echo "Branch name is ${{ github.ref }}"
            echo "::set-output name=container_port::${CONTAINER_PORT}"
          
      - name: Run Docker container
        run: |
            docker run -d -p ${{ steps.determine_port.outputs.container_port }}:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ steps.commit_hash.outputs.COMMIT_HASH }}
  
