name: Staging-Prod

on:
    push:
        branches:
          - main
          - staging
        tags:
          - '[0-9].+[0-9].+[0-9]'


jobs:
  build:
    runs-on:
      - self-hosted
      - my-host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:latest
      
      - name: Stop processes on port 3001
        run: |
            sudo lsof -t -i :3001 | xargs kill -9 || true
          
      - name: Run Docker container
        run: |
            docker run -d -p 3001:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-newsletter-apis:${{ github.sha }}
  
